version: '3.8'

services:
  
  feedbacksql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: feedbacksql
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "SuperSafePass123"
      ACCEPT_EULA: "Y"
    volumes:
      - feedback_volume:/var/opt/mssql

  feedback-service:
    image : bumblez/labb2cleancode-feedback-service
    container_name: FeedbackService
    depends_on:
        - feedbacksql
    ports:
        - "5006:8080"
    environment:
      ConnectionStrings_DefaultConnection: "Server=feedbacksql;Database=MyDatabase;User Id=sa;Password=SuperSafePass123;TrustServerCertificate=True;"

volumes:
  feedback_volume: {}