name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/labb2cleancode-feedback-service:latest -f FeedbackService/Dockerfile .
      
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/labb2cleancode-feedback-service:latest 

    - name: Log out from Docker
      run: docker logout
